site_name: EcoTrace
site_description: High-precision carbon tracking engine for production Python.
site_author: Emre Ozkal
repo_url: https://github.com/Zwony/ecotrace
repo_name: Zwony/ecotrace

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")

nav:
  - Home: index.md
  - Usage: USAGE.md
  - API Reference: api.md
  - Architecture: ARCHITECTURE.md
  - Integrations:
      - Flask: USAGE.md
      - FastAPI: USAGE.md
  - Community:
      - Contributing: CONTRIBUTING.MD
      - Code of Conduct: CODE_OF_CONDUCT.MD
      - Security: SECURITY.MD
      - Support: SUPPORT.md
  - History:
      - Changelog: CHANGELOG.md
      - v1.0.1: history/releases/RELEASE_v1.0.1.md
      - v0.9.0: history/releases/RELEASE_v0.9.0.md
      - v0.8.0: history/releases/RELEASE_v0.8.0.md
      - v0.7.1: history/releases/RELEASE_v0.7.1.md
      - v0.7.0: history/releases/RELEASE_v0.7.0.md
      - v0.6.1: history/releases/RELEASE_v0.6.1.md
      - v0.6.0: history/releases/RELEASE_v0.6.0.md
      - v0.5.2: history/releases/RELEASE_v0.5.2.md
      - v0.5.1: history/releases/RELEASE_v0.5.1.md
      - v0.5.0: history/releases/RELEASE_v0.5.0.md
      - v0.4.0: history/releases/RELEASE_v0.4.0.md
